name: deploy-site
env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  REACT_APP_GITHUB_TOKEN: ${{ secrets.PORTFOLIO_TOKEN }} # This is automatically set by Github Actions
  USE_GITHUB_DATA: "true"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - build/**
      - public/**
      - .github/workflows/deploy.yml

defaults:
  run:
    working-directory: src

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: update npm
        run: npm install -g npm@latest

      - name: Install dependencies and deploy
        run: |
          npm install
          npm run predeploy

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.PORTFOLIO_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
