name: deploy-site

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - build/**
      - public/**
      - .github/workflows/deploy.yml

defaults:
  run:
    working-directory: src

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: git config --global user.email "hendrickgalarzahernandez@gmail.com"
        working-directory: ${{ github.workspace }}
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run predeploy
      - run: npm run deploy

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
