name: deploy-site

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - build/**
      - public/**
      - .github/workflows/deploy.yml

defaults:
  run:
    working-directory: src

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "hendrickghxd@gmail.com"
          git config --global user.name "Hendrick Galarza Hernandez"
        working-directory: ${{ github.workspace }}

      - name: Local deploy
        uses: actions/checkout@v2
        run: |
          npm install
          npm run predeploy
          npm run deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
